/*
 *  Copyright 2023 EPAM Systems
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

const expect = require('chai').expect;
const { ReportingApi } = require('@reportportal/agent-js-webdriverio');

describe('Set testCaseId for suite/test', () => {
  before(() => {
    ReportingApi.setTestCaseId('TestCaseIdForTheSuite');
  });

  it('should have the explicit testCaseId', () => {
    ReportingApi.setDescription('This test case contains explicit test case id');
    ReportingApi.addAttributes([
      {
        key: 'feature',
        value: 'ExplicitTestCaseId',
      },
    ]);
    ReportingApi.setTestCaseId('TestCaseIdForTheTest');
    expect(true).to.be.true;
  });

  it('should have the autogenerate testCaseId', () => {
    ReportingApi.setDescription('This test case contains automatically generated testcase id');
    ReportingApi.addAttributes([
      {
        key: 'feature',
        value: 'AutoGeneratedTestCaseId',
      },
    ]);
    expect(true).to.be.true;
  });
});
