apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  concurrency: 10
  metadata:
    tags:
      - e2e
playwright:
  version: package.json # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
  configFile: playwright.config.ts # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#configfile for a list of supported configuration files.
rootDir: ./
npm:
  packages:
    "@reportportal/agent-js-playwright": "^5.1.11"
suites:
  - name: "Chromium Win"
    platformName: "Windows 11"
    screenResolution: "1440x900"
    testMatch: ["tests/basic/.*\\.spec\\.ts"]
    params:
      browserName: "chromium"
      project: "basic" # Runs the project that's defined in `playwright.config.js`
